# Generated by Django 3.2.4 on 2023-02-28 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_alter_comment_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='content',
        ),
    ]
