# Generated by Django 3.2.17 on 2023-02-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='modified_on',
            new_name='updated_at',
        ),
    ]
